name: Copy of Face Detector on Camera
description: This example showcases face detection within a live feed from a USB camera.
ports: []
bricks:
- arduino:video_object_detection:
    model: face-detection
- arduino:web_ui: {}
icon: ☺️
