M48
; DRILL file {KiCad (6.0.11-0)} date 2023 October 17, Tuesday 10:34:45
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-10-17T10:34:45+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.11-0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.600
%
G90
G05
T1
X107.821Y-50.053
T1
X101.946Y-50.053G85X101.696Y-50.053
G05
T0
M30
